export const F={花:"Flower",銅:"Copper",草:"Grass",鐵:"Iron",木:"Wood",赤:"RedIron",鋼:"Steel",鋁:"Alum",
皮:"Leather",晶:"Crystal",骨:"Bone",魔:"MagicJade",玉:"Jade",鉛:"Lead",寶:"Gem",白:"Platinum",
結:"Cluster",鈦:"Titan",銀:"Silver",金:"Gold",鑽:"Diamond",石:"Rock",羽:"Feather",葉:"Leaf",錫:"Tin"};
export const S={杖:"Staff",刀:"Blade",劍:"Sword",衣:"Armor",腕:"Bracer",帽:"Helm",鞋:"Boots",槌:"Hammer",
弓:"Bow",特:"Accessory",物:"Material",斧:"Axe",爪:"Claw",槍:"Spear",魔:"Fan"};
export const D=[
[2,0,"Star Dust · Sky","星耀之塵·空","物",[],"—","",'mat'],
[3,0,"Star Dust · Fire / Wind / Water / Earth","星耀之塵·火/風/水/地","物",[],"—","Whale Island monster drops",'mat'],
[4,8,"Starlight Wand","星輝法杖","杖",["花"],"MATK+5 MDEF+5","Star Dust + Flower Honey",'magic'],
[4,8,"Starmark Sabre","星紋彎刀","刀",["銅"],"ATK+5 DEF+5","Star Dust + Copper Ore",'phys'],
[5,10,"Starmark Robe","星紋法衣","衣",["花"],"MDEF+6 DEF+4","Star Dust + Flower Honey",'magic'],
[5,10,"Starmark Scale Armor","星紋鱗甲","衣",["銅"],"DEF+6 MDEF+4","Star Dust + Copper Ore",'phys'],
[7,14,"Starlight Gloves","星輝手套","腕",["花"],"MDEF+6","5 Star + 5 Flower",'magic'],
[7,14,"Starmark Bracers","星紋護腕","腕",["銅"],"DEF+9","5 Star + 5 Copper (Bronze Mat.)",'phys'],
[8,16,"Starlight Crown","星輝法冠","帽",["花"],"MATK+9","5 Star + 5 Flower",'magic'],
[8,16,"Starmark Helm","星紋頭盔","帽",["銅"],"DEF+9","5 Star + 5 Copper (Bronze Mat.)",'phys'],
[9,18,"Starlight Boots","星輝法靴","鞋",["花"],"MATK+13 SPD+1","5 Star + 5 Flower + Vol.1",'magic'],
[9,18,"Starmark War Boots","星紋戰靴","鞋",["銅"],"DEF+13 SPD+1","5 Star + 5 Copper + Vol.1",'phys'],
[11,22,"Starfire Hammer","星火之槌","槌",["草"],"MATK+13 SPD+1","7 Star + 6 Grass (Priest Hat) + book",'magic'],
[11,54,"Star Ring Longsword","星環長劍","劍",["鐵"],"ATK+12 SPD+10","5★+5 Iron+Vol.2 · 7★+7 Iron · 9★+9 Iron (Australia)",'phys'],
[13,26,"Starfire Robe","星火法袍","衣",["草"],"MDEF+9 SPD+5","11 Star + 10 Grass + book",'magic'],
[13,26,"Star Ring Battle Dress","星環戰衣","衣",["鐵"],"DEF+9 SPD+5","11★+11 Iron (Indian Sabre) · buy India",'phys'],
[15,30,"Starfire Gloves","星火手套","腕",["草"],"MATK+17 SPD+1","11 Star + 11 Grass + book",'magic'],
[15,30,"Star Ring Bracers","星環護腕","腕",["鐵"],"DEF+17 SPD+1","11 Star + 11 Iron (Indian Sabre)",'phys'],
[17,34,"Starfire Magic Crown","星火魔冠","帽",["草"],"MDEF+11 DEF+8","11 Star + 11 Grass + Vol.2",'magic'],
[17,34,"Star Ring Helm","星環頭盔","帽",["鐵"],"DEF+11 MDEF+6","15★+15 Iron (Katana) · buy Japan",'phys'],
[19,38,"Starfire Magic Boots","星火魔靴","鞋",["草"],"MDEF+12 SPD+5","15 Star + 15 Grass + Vol.2",'magic'],
[19,38,"Star Ring War Boots","星環戰靴","鞋",["鐵"],"DEF+12 SPD+5","15 Star + 15 Iron (Katana) + Vol.2",'phys'],
[21,42,"Star Splendor War Bow","星華戰弓","弓",["木"],"ATK+16 SPD+28","17★+17 Wood+Vol.2 · 19★+19 Wood",'phys'],
[22,0,"★ Star Essence","星耀精華","物",[],"—","21 Star + 20 Bone (Wolf Fang) + Vol.2",'mat'],
[23,46,"Star Splendor Robe","星華法袍","衣",["木"],"MATK+18 SP+60","21 Star + 21 Wood + book",'magic'],
[23,46,"Star Edge Battle Armor","星鋒戰甲","衣",["赤"],"DEF+18 HP+60","21 Star + 21 Red Iron + Vol.2",'phys'],
[24,0,"★ Star Goldwood","星耀金木","物",[],"—","21 Star + 20 Bone (Wolf Fang) + Vol.2",'mat'],
[25,50,"Star Splendor Gloves","星華手套","腕",["木"],"MDEF+16 DEF+10","21 Star + 21 Wood + Vol.2",'magic'],
[25,50,"Star Edge Bracers","星鋒護腕","腕",["赤"],"DEF+16 MDEF+10","21 Star + 21 Red Iron + Vol.2",'phys'],
[26,0,"Star Glass","星耀琉璃","物",[],"—","21 Star + 20 Bone (Wolf Fang) + Vol.2",'mat'],
[27,54,"Star Splendor Crown","星華法冠","帽",["木"],"MDEF+21 DEF+7","21 Star + 21 Wood + Vol.2",'magic'],
[27,54,"Star Splendor Helm","星華頭盔","帽",["赤"],"DEF+20 MDEF+8","21 Star + 21 Red Iron + Vol.2",'phys'],
[28,0,"Star Mithril","星耀密銀","物",[],"—","25 Star + Black Jade + book",'mat'],
[29,58,"Star Splendor Boots","星華法靴","鞋",["木"],"DEF+20 SPD+10","25 Star + 24 Wood + Vol.2",'magic'],
[29,58,"Star Peak War Boots","星峰戰靴","鞋",["赤"],"DEF+35 SPD−5","25 Star + 25 Red Iron + Vol.2",'phys'],
[30,60,"Stardust Blade","星塵刀","刀",["鋼"],"ATK+40 SPD+20","Stardust set · 25★+25 Steel+Vol.2",'phys'],
[30,60,"Stardust Sword","星塵劍","劍",["鋼","骨"],"MATK+40 SPD+20","Stardust set · 27★+27 Steel+26 Bone+book",'magic'],
[30,60,"Stardust Hat","星塵帽","帽",["鋁"],"SPD+21 HP+100","Stardust set · 27★+27 Alum+book",'phys'],
[30,60,"Stardust Bracers","星塵護腕","腕",["皮"],"DEF+21 SP+100","Stardust set · 25★+25 Leather+Vol.2",'phys'],
[30,60,"Stardust Tunic","星塵上衣","衣",["草"],"ATK+16 MATK+16","Stardust set · 25★+25 Grass+book",'magic'],
[30,60,"Stardust Shoes","星塵短鞋","鞋",["赤"],"DEF+5 MDEF+26","Stardust set · 25★+25 Red Iron+Vol.2",'phys'],
[30,60,"Star Splendor Ring","星華戒指","特",["晶"],"MATK+25 MDEF+6","27 Star + 26 Crystal + book",'magic'],
[30,60,"Star Edge Ring","星鋒戒指","特",["晶"],"ATK+25 DEF+6","27 Star + 26 Crystal + book",'phys'],
[31,62,"Star Frost Magic Axe","星霜魔斧","斧",["魔","玉"],"MATK+31 HP+40","Star-Steel-Iron-Steel (Primary)",'magic'],
[31,62,"Star Burst Blade Claw","星爆刃爪","爪",["赤","鉛"],"ATK+32 SPD+32","Star-Copper-Gold-Iron (Primary) · 25★+25赤+25鉛+book",'phys'],
[32,0,"Star Feather","星耀之羽","物",[],"—","",'mat'],
[33,66,"Star Frost Robe","星霜法袍","衣",["魔","皮"],"MDEF+34","Star-Titan-Gold-Crystal (Primary)",'magic'],
[33,66,"Star Burst Battle Armor","星爆戰甲","衣",["鋼","骨"],"DEF+34","27★+27 Steel+26 Bone+book",'phys'],
[34,0,"Star Ice Crystal","星耀冰晶","物",[],"—","",'mat'],
[35,70,"Star Frost Gloves","星霜手套","腕",["玉","魔"],"MDEF+26 SPD+10","",'magic'],
[35,70,"Star Burst Bracers","星爆護腕","腕",["鋼","赤"],"DEF+26 SPD+10","Star-Copper-Iron-Steel (Primary)",'phys'],
[37,74,"Star Frost Crown","星霜法冠","帽",["魔","晶"],"MDEF+28 DEF+10","Star-Flower-Grass-Gold (Primary) — cannot be compounded normally",'magic'],
[37,74,"Star Burst Helm","星爆頭盔","帽",["鋼","鉛"],"DEF+28 MDEF+10","Star-Titan-Gold-Crystal (Primary)",'phys'],
[38,0,"Star Divine Rune","星耀神紋","物",[],"—","",'mat'],
[39,78,"Star Frost Boots","星霜法靴","鞋",["魔","皮"],"MDEF+30 SPD+10","Star-Copper-RedIron-Gem (Primary)",'magic'],
[39,78,"Star Burst War Boots","星爆戰靴","鞋",["鋼","骨"],"DEF+40 SPD−5","",'phys'],
[40,80,"Star Frost Necklace","星霜項鍊","特",["結","魔"],"MATK+30 MDEF+11","Star-Titan-Steel-Gold (Primary) — compounds normally",'magic'],
[40,80,"Star Burst Necklace","星爆項鍊","特",["結","魔"],"ATK+30 DEF+11","Star-Titan-Steel-Gold (Primary) — compounds normally",'phys'],
[41,82,"Constellation Magic Staff","星辰魔杖","杖",["寶","晶","白"],"MATK+42 MDEF+40","Star-RedIron-Copper-Gem-Titan (Primary)",'magic'],
[41,82,"Firmament Steel Axe","星穹鋼斧","斧",["鈦","鋼","金"],"ATK+42 DEF+40","",'phys'],
[43,86,"Constellation Robe","星辰法袍","衣",["寶","羽","白"],"MDEF+44","",'magic'],
[43,86,"Firmament Battle Armor","星穹戰甲","衣",["鋼","鑽","鈦"],"DEF+44","",'phys'],
[45,90,"Constellation Gloves","星辰手套","腕",["寶","白","結"],"MDEF+36 SPD+10","38★+37 Gem+37 Platinum+37 Cluster",'magic'],
[45,90,"Firmament Bracers","星穹護腕","腕",["鈦","鋼","結"],"DEF+36 SPD+10","",'phys'],
[47,94,"Constellation Crown","星辰法冠","帽",["銀","寶","鈦"],"MDEF+32 DEF+15","",'magic'],
[47,94,"Firmament Helm","星穹頭盔","帽",["鋼","鑽","鈦"],"DEF+32 MDEF+15","",'phys'],
[49,98,"Constellation Boots","星辰法靴","鞋",["金","寶","骨"],"MDEF+38 SPD+12","",'magic'],
[49,98,"Firmament War Boots","星穹戰靴","鞋",["鐵","錫","鈦"],"DEF+40 SPD+10","",'phys'],
[51,0,"Flawless Star Crystalwood","無暇星耀晶木","物",[],"—","45 Star+44 Jade · 47 Star+47 Jade",'mat'],
[51,102,"Starmark Magic Sword","星痕魔劍","劍",["木","金","銀","晶"],"MATK+80 · RANDOM","Starmark set",'magic'],
[51,102,"Starshadow Scythe","星影鐮刀","刀",["花","葉","木","鐵"],"ATK+80 · RANDOM","Starshadow set",'phys'],
[52,104,"Firmament Magic Ring","星穹法戒","刀",["鐵","錫","鋁","玉"],"MATK+32 · RANDOM","",'magic'],
[52,104,"Firmament War Ring","星穹戰戒","刀",["金","銀","銅","鐵"],"ATK+32 · RANDOM","",'phys'],
[53,106,"Starmark Robe","星痕法袍","衣",["寶","鑽","晶","石"],"HP+560 · RANDOM","Starmark set",'magic'],
[53,106,"Starshadow Battle Armor","星影戰甲","衣",["鐵","鋁","玉","寶"],"HP+560 · RANDOM","Starshadow set",'phys'],
[54,0,"Flawless Star Feather","無暇星耀之羽","物",[],"—","",'mat'],
[54,108,"Starshadow Magic Sword","星影法劍","劍",["鈦","皮","羽","骨"],"ATK+83 · RANDOM","",'phys'],
[54,108,"Firmament War Blade","星穹戰刀","刀",["銅","晶","石","鈦"],"ATK+83 · RANDOM","",'phys'],
[55,110,"Starmark Gloves","星痕手套","腕",["花","葉","木","晶"],"DEF+40 · RANDOM","Starmark set",'magic'],
[55,110,"Starshadow Bracers","星影護腕","腕",["花","鐵","羽","骨"],"DEF+40 · RANDOM","Starshadow set",'phys'],
[56,112,"Firmament Dragon Fan","星穹龍扇","魔",["銀","銅","鐵","玉"],"MATK+85 · RANDOM","",'magic'],
[56,112,"Firmament War Halberd","星穹戰戟","槍",["木","金","銀","銅"],"ATK+85 · RANDOM","",'phys'],
[57,0,"Flawless Star Glass","無暇星耀琉璃","物",[],"—","",'mat'],
[57,114,"Starmark Crown","星痕法冠","帽",["鋁","玉","寶","晶"],"MDEF+35 · RANDOM","Starmark set",'magic'],
[57,114,"Starshadow Helm","星影頭盔","帽",["鐵","玉","寶","鑽"],"MDEF+35 · RANDOM","Starshadow set",'phys'],
[58,116,"Firmament Magic Staff","星穹法杖","杖",["鑽","玉","石","鈦"],"MATK+87 · RANDOM","",'magic'],
[58,116,"Firmament Claw","星穹爪","爪",["銀","寶","鑽","晶"],"ATK+87 · RANDOM","",'phys'],
[59,0,"Flawless Star Mithril","無暇星耀秘銀","物",[],"—","",'mat'],
[59,118,"Starmark Boots","星痕法靴","鞋",["花","晶","羽","骨"],"SPD+40 · RANDOM","Starmark set",'magic'],
[59,118,"Starshadow War Boots","星影戰靴","鞋",["鐵","鈦","皮","羽"],"SPD+40 · RANDOM","Starshadow set",'phys'],
[60,120,"Starmark Ring","星痕戒指","特",["金","銀","銅","晶"],"MATK+40 · RANDOM","Starmark set",'magic'],
[60,120,"Starshadow Ring","星影戒指","特",["葉","木","金","鐵"],"ATK+40 · RANDOM","Starshadow set",'phys']
];
