// Interface strings. Thai first-class — every key must exist in both languages.
export const LANGS = ['th', 'en'];
export const DEFAULT_LANG = 'th';

export const UI = {
  en: {
    dir: 'ltr',
    site: {
      name: 'Star Drift',
      full: 'Wonderland Re: Star Ark — data',
      tagline:
        'The Taiwan-server compounding data for Wonderland Online Re: Star Ark, in English and Thai.',
    },
    view: { auto: 'Auto', mobile: 'Mobile', desktop: 'Desktop', viewHelp: 'Switch layout: auto / mobile / desktop' },
    nav: {
      compounds: 'Compounds',
      materials: 'Materials',
      simulator: 'Planner',
      quests: 'Quests',
      about: 'About',
      switchLang: 'ไทย',
    },
    common: {
      search: 'Search name, Chinese, recipe…',
      allFamilies: 'All families (main + secondary)',
      allSlots: 'All slots',
      allTowns: 'All towns',
      rank: 'Rank',
      lv: 'Lv',
      item: 'Item',
      slot: 'Slot',
      families: 'Families',
      stats: 'Stats',
      recipe: 'Recipe',
      source: 'Where to get it',
      showing: '{n} of {total}',
      noResults: 'Nothing matches those filters.',
      reset: 'Reset',
      rankFrom: 'from',
      rankTo: 'to',
      untranslated: 'Thai name not yet confirmed',
      confirmedTh: 'Thai name confirmed in the live client',
      lvWarning: 'The source sheet’s equip level contradicts rank × 2 here',
      partialFamily: 'This family is only covered to rank 30 in the source',
      note: 'Note',
      legendKk: 'confirmed in the Thai client',
      legendDefault: 'no badge = reported by the community sheet',
      legendThOk: 'Thai name confirmed',
      legendThNo: 'Thai name still a translation',
      legendWarn: 'level and rank disagree in the source',
      statFilter: 'stat filter',
      stat: 'stat',
      value: 'value',
      sort: 'sort',
      sortDefault: 'by family',
      basket: 'Shortlist',
      addShort: 'Add',
      inBasket: 'Added',
      basketAdd: 'Add to the planner shortlist',
      basketRemove: 'Remove from the shortlist',
      basketHelp: 'Items you starred here appear in the planner, ready to drop into a tree',
      remove: 'remove',
      where: 'Sold at',
      price: 'Price',
      shopOnly: 'Sold in shops',
      unknownSource: 'source ?',
      noShop: 'Not sold in any shop',
      shop: 'Shop',
      allShops: 'All shops',
    },
    home: {
      eyebrow: 'Taiwan server data · Thai client',
      h1: 'Wonderland Re: Star Ark',
      lede:
        'A year of Taiwan-server research, translated. Compounding recipes, where every material comes from, and which shops you can actually reach on the Thai map.',
      cta: 'Open the compound database',
      statsTitle: 'What is in here',
      rulesTitle: 'Read this if you read nothing else',
      rules: [
        ['Compounding is the whole game.', 'Gear is crafted, not dropped. Compounded gear massively outclasses shop gear at the same level.'],
        ['Item rank = equip level ÷ 2.', 'Everything in crafting is about landing on an exact rank. The Thai client prints it as เลเวลไอเทม.'],
        ['The lowest-ranked ingredient sets the base.', 'Never mix a rank-25 gem with a rank-1 stick — you throw away the expensive one.'],
        ['Slot 1 chooses the result table.', 'The [หลัก] primary family decides what you can make. Order matters.'],
        ['Encyclopedia Vol. 1–4 go last.', 'They add +1…+4 rank and success rate, and they are the expensive part of any recipe.'],
        ['Primary alchemy to wash, Superior to finish.', 'Convert materials cheaply at low rank; save Superior for the final climb.'],
        ['Combo attack gives 2–2.5× EXP.', 'Leave one monster, debuff it, then player and companion both ultimate.'],
        ['Fire hits hardest and folds fastest.', 'Fire grows ATK at lv×2.0 against everyone else’s 1.4, but takes ×0.5 from water. Water→Fire at ×1.6 is the hardest counter in the game.'],
      ],
      trustTitle: 'How much to trust a row',
      trustLede:
        'Every row carries a confidence tag. Check it before you spend an Encyclopedia volume or a rare gem.',
      sourceTitle: 'Where this comes from',
      sourceBody:
        'The Taiwan server launched in June 2025 and has a year of community research behind it; the Thai server opened in July 2026. So the source of truth here is Taiwanese: the 「星飄」 community compounding sheet compiled by 苦茶, maintained to 2026-05-30, cross-checked against the Thai client wherever possible. Names are matched by rank and stat profile, never by name alone.',
      warnTitle: 'Two things this site is not',
      warnBody:
        'It is not a live mirror of the game — the source data stops at 2026-05-30. And Thai item names are translations unless marked as confirmed in the client. A Thai name you cannot find in your own client is worse than an English one, so check the rank and the stats first.',
    },
    compounds: {
      title: 'Compound database',
      lede:
        'Every compounding recipe from the Taiwan community sheet, Star family included. Filter by family, slot, rank, or stat — “sword with ATK > 35” is a slot plus one stat filter. Read the recipe column as material families, not item names — “18 Pure Iron + Wolf Fang” means any rank-18 Pure Iron item plus a Wolf Fang.',
      verifiedOnly: 'Verified only',
    },
    materials: {
      title: 'Shops & materials',
      lede:
        'Which shop sells which material, at what rank and price, and whether that town is open on the Thai server yet. Turn off “Sold in shops” to see the other 74 materials you have to drop, gather or craft.',
      openOnly: 'Buyable on the Thai map today',
      openOnlyHelp:
        'The September 2026 patch added China Fishing Village, Bangkok and Madagascar. Shop towns open on the Thai server now: Australia, Easter Island, Calcutta, Antarctica, China Fishing Village and Bangkok. Egypt — the whole rank-18 tier — Japan, Korea, Chang\u2019an, Athens and Whale Island are still closed.',
      where: 'Sold at',
      price: 'Price',
      shopOnly: 'Sold in shops',
      unknownSource: 'source ?',
      noShop: 'Not sold in any shop',
      shop: 'Shop',
      drop: 'Drop',
      gather: 'Gather',
      craft: 'Craft',
      scroll: 'Alchemy scroll',
      cheapest: 'Cheapest of family',
      highest: 'Highest buyable',
      key: 'Key material',
      priceLegacy: 'price is legacy data, may be wrong in Re',
      priceRe: 'price confirmed in the Re sheet',
      closed: 'closed on TH',
      open: 'open on TH',
      unverified: 'status unknown',
      notInRe: 'does not exist in Re',
    },
    star: {
      title: 'The Star family',
      lede:
        'The Re-exclusive 星耀 / ประกายดาว line — it does not exist in the original Wonderland Online, and it runs deeper than any other family, to rank 60.',
      pairNote:
        'The family is built in pairs. At almost every rank there are two items: a magic piece pairing Star with a soft family, and a physical piece pairing Star with a metal. Same rank, same slot, mirrored stats.',
      all: 'All',
      magic: 'Magic',
      phys: 'Physical',
      mat: 'Materials',
      random: 'stats roll randomly',
      bands: {
        'Dust tier — Star + Flower / Copper': 'Dust tier — Star + Flower / Copper',
        'Early — Star + Grass / Iron': 'Early — Star + Grass / Iron',
        'Mid — Star + Wood / Pure Iron, then the Stardust set': 'Mid — Star + Wood / Pure Iron, then the Stardust set',
        'High — two secondaries per piece': 'High — two secondaries per piece',
        'Constellation & Firmament — three secondaries': 'Constellation & Firmament — three secondaries',
        'Endgame — four secondaries, random stats': 'Endgame — four secondaries, random stats',
      },
    },
    sim: {
      title: 'Compound planner',
      lede:
        'Build your own compounding tree. The item you want sits at the top; add whatever you plan to combine beneath it — any item, any material, or your own text — as deep as 20 levels. Then save it as a picture and follow the steps from the bottom up.',
      caveat:
        'Nothing here is enforced or suggested. It is your note. The ⇣ button on an item pulls that item’s recipe from the database as a starting point; edit or delete anything it adds.',
      pickTarget: 'Search for the item you want to make…',
      pickAny: 'Search item or material…',
      freeText: 'or type anything',
      or: 'or',
      emptyHint: 'Choose a target item above to start a plan.',
      steps: 'steps',
      depth: 'depth',
      stepsTitle: 'The climb, bottom up',
      stepsHelp: 'Every node with children becomes a step. Notes in [brackets] come from the node’s note field.',
      expandHint: 'Add children under the target (＋) to get steps.',
      notePh: 'note… (×2, buy at Egypt)',
      addChild: 'Add an ingredient beneath this',
      loadRecipe: 'Load this item’s recipe from the database',
      remove: 'Remove',
      savePng: 'Save as picture',
      basketTitle: 'Shortlist',
      basketHelp: 'Starred on the compound page. Select a node in the tree, then add an item beneath it.',
      basketEmpty: 'Nothing here yet — star items (☆) on the compound page.',
      basketAsRoot: 'Use as target',
      basketAddUnder: 'Add under',
      basketNoSel: 'select a node first',
      basketClear: 'Clear shortlist',
      selected: 'selected',
      fit: 'Fit',
      zoomHint: 'scroll to zoom · drag scrollbars to pan',
      newPlan: 'New plan',
      confirmNew: 'Clear this plan and start over?',
      material: 'Material',
      book: 'Book',
      anyBook: 'Encyclopedia (any Vol.)',
      where: 'Sold at',
      price: 'Price',
      shopOnly: 'Sold in shops',
      unknownSource: 'source ?',
      noShop: 'Not sold in any shop',
      shop: 'Shop',
      open: 'open on TH',
      closed: 'closed on TH',
    },
    glossary: {
      title: 'Glossary',
      lede:
        'Chinese ⇄ English ⇄ Thai. The research is all in Traditional Chinese and your client is in Thai — this is the bridge.',
      sections: {
        system: 'System terms',
        ui: 'Thai client interface',
        stats: 'Stats and elements',
        jobs: 'Jobs and status effects',
        catalysts: 'Key catalysts',
      },
      confirmedNote: 'Read off the live Thai client',
    },
    quests: {
      title: 'Quests',
      lede: 'Quest lists by category. Most rows are still Legacy WLO data — the Taiwan board that holds the current Re lists blocks automated reading, so treat a legacy row as a strong hint, not as the Thai client\u2019s text.',
      search: 'Search quest, NPC, place, reward…',
      allTypes: 'All quest types',
      type: 'Type',
      quest: 'Quest',
      where: 'Where',
      req: 'Requirement',
      reward: 'Reward',
      stars: 'Stars',
      detail: 'Steps / notes',
      earn: 'earns',
      spend: 'costs',
      reOnly: 'Re-confirmed only',
      source: 'source',
      sourceKinds: {
        wiki: 'EN wiki',
        cnwiki: '中文 wiki',
        guide: 'Guide',
        reguide: 'Re guide',
        index: 'Quest index',
        baha: '巴哈 thread',
        board: 'Re board',
        search: 'Search',
      },
      sourceHelp: {
        wiki: 'Wonderland Online Fandom wiki — the quest page, usually with screenshots',
        cnwiki: 'Bahamut\u2019s Chinese encyclopedia for the original release — the most detailed walkthroughs',
        guide: 'An English walkthrough covering this quest',
        reguide: 'A Re: Star Ark guide site',
        index: 'Fandom\u2019s master quest index, by area',
        baha: 'The Taiwan board thread this row came from',
        board: 'The Re: Star Ark board on Bahamut — search it for this quest',
        search: 'Google search for this quest name',
      },
      counts: '{n} of {total} quests · {re} confirmed for Re',
      noResults: 'No quest matches those filters.',
      gap: 'Known gap: the full Re main-quest and side-quest lists are not published anywhere reachable. If you can read a quest name off your client, tell KK and it gets added.',
    },
    footer: {
      source:
        'Source: the Re community compounding sheet 「星飄」 by 苦茶 and named contributors, maintained 2025-06-25 → 2026-05-30. English and Thai names are translations unless marked confirmed.',
      match: 'Match items by rank and stats, which are language-independent — not by name.',
      updated: 'Data as of',
    },
  },

  th: {
    dir: 'ltr',
    site: {
      name: 'Star Drift',
      full: 'Wonderland Re: Star Ark — ฐานข้อมูล',
      tagline:
        'ข้อมูลการรวมไอเทมจากเซิร์ฟไต้หวันของ Wonderland Online Re: Star Ark ทั้งภาษาไทยและอังกฤษ',
    },
    view: { auto: 'อัตโนมัติ', mobile: 'มือถือ', desktop: 'จอใหญ่', viewHelp: 'สลับเลย์เอาต์: อัตโนมัติ / มือถือ / จอใหญ่' },
    nav: {
      compounds: 'สูตรรวมไอเทม',
      materials: 'ร้านค้า',
      simulator: 'วางแผนการรวม',
      quests: 'เควส',
      about: 'เกี่ยวกับ',
      switchLang: 'EN',
    },
    common: {
      search: 'ค้นหาชื่อ ภาษาจีน หรือสูตร…',
      allFamilies: 'ทุกตระกูลวัสดุ (หลัก + รอง)',
      allSlots: 'ทุกช่องสวมใส่',
      allTowns: 'ทุกเมือง',
      rank: 'เลเวลไอเทม',
      lv: 'ลิมิต',
      item: 'ไอเทม',
      slot: 'ประเภท',
      families: 'วัสดุโครงสร้าง',
      stats: 'ค่าสถานะ',
      recipe: 'สูตร',
      source: 'หาได้จากที่ไหน',
      showing: '{n} จาก {total}',
      noResults: 'ไม่พบรายการที่ตรงกับตัวกรอง',
      reset: 'ล้างตัวกรอง',
      rankFrom: 'ตั้งแต่',
      rankTo: 'ถึง',
      untranslated: 'ยังไม่ยืนยันชื่อไทย',
      confirmedTh: 'ยืนยันชื่อไทยจากในเกมแล้ว',
      lvWarning: 'ลิมิตเลเวลในต้นฉบับไม่ตรงกับ เลเวลไอเทม × 2',
      partialFamily: 'ต้นฉบับมีข้อมูลตระกูลนี้ถึงเลเวลไอเทม 30 เท่านั้น',
      note: 'หมายเหตุ',
      legendKk: 'ยืนยันในไคลเอนต์ไทยแล้ว',
      legendDefault: 'ไม่มีป้าย = ข้อมูลจากตารางคอมมูนิตี้',
      legendThOk: 'ยืนยันชื่อไทยแล้ว',
      legendThNo: 'ชื่อไทยยังเป็นคำแปล',
      legendWarn: 'ลิมิตเลเวลกับเลเวลไอเทมในต้นฉบับไม่ตรงกัน',
      statFilter: 'กรองค่าสถานะ',
      stat: 'ค่าสถานะ',
      value: 'ค่า',
      sort: 'เรียงลำดับ',
      sortDefault: 'ตามตระกูล',
      basket: 'ลิสต์วางแผน',
      addShort: 'เพิ่ม',
      inBasket: 'อยู่ในลิสต์',
      basketAdd: 'เพิ่มเข้าลิสต์วางแผน',
      basketRemove: 'เอาออกจากลิสต์',
      basketHelp: 'ไอเทมที่ติดดาวไว้จะไปรอในหน้าวางแผน พร้อมลากเข้าแผนผัง',
      remove: 'ลบ',
      where: 'ร้านที่ขาย',
      price: 'ราคา',
      shopOnly: 'เฉพาะที่มีขายในร้าน',
      unknownSource: 'ยังไม่ทราบที่มา',
      noShop: 'ไม่มีร้านไหนขาย',
      shop: 'ร้านค้า',
      allShops: 'ทุกร้านค้า',
    },
    home: {
      eyebrow: 'ข้อมูลเซิร์ฟไต้หวัน · สำหรับไคลเอนต์ไทย',
      h1: 'Wonderland Re: Star Ark',
      lede:
        'งานค้นคว้าจากเซิร์ฟไต้หวันตลอดหนึ่งปี แปลไว้ให้แล้ว — สูตรรวมไอเทม แหล่งที่มาของวัตถุดิบทุกชิ้น และร้านไหนที่เปิดให้ซื้อได้จริงบนแมพไทย',
      cta: 'เปิดฐานข้อมูลสูตรรวม',
      statsTitle: 'ในนี้มีอะไรบ้าง',
      rulesTitle: 'ถ้าจะอ่านแค่อย่างเดียว อ่านตรงนี้',
      rules: [
        ['การรวมไอเทมคือหัวใจของเกม', 'อุปกรณ์ได้จากการรวม ไม่ใช่ดรอป ของที่รวมเองแรงกว่าของร้านที่เลเวลเดียวกันมาก'],
        ['เลเวลไอเทม = ลิมิตเลเวล ÷ 2', 'ทุกอย่างในการคราฟคือการทำให้ได้เลเวลไอเทมที่ต้องการพอดี ไคลเอนต์ไทยแสดงค่านี้ตรง ๆ ในชื่อ เลเวลไอเทม'],
        ['วัตถุดิบที่เลเวลต่ำสุดเป็นตัวกำหนดฐาน', 'อย่าเอาอัญมณีเลเวล 25 ไปรวมกับไม้เลเวล 1 เพราะของแพงจะเสียเปล่า'],
        ['ช่องที่ 1 เป็นตัวเลือกตารางผลลัพธ์', 'วัสดุที่ติดป้าย [หลัก] เป็นตัวกำหนดว่าจะรวมออกมาเป็นอะไร ลำดับการใส่จึงสำคัญ'],
        ['หนังสือเล่ม 1–4 ใส่เป็นอันสุดท้ายเสมอ', 'เพิ่มเลเวลไอเทม +1…+4 และเพิ่มโอกาสสำเร็จ และเป็นส่วนที่แพงที่สุดของทุกสูตร'],
        ['ขั้นต้นไว้ล้างวัสดุ ขั้นสูงไว้ปิดจ็อบ', 'ใช้วิชาขั้นต้นแปลงวัสดุที่เลเวลต่ำ ๆ เพราะถูก แล้วเก็บวิชาขั้นสูงไว้ไต่เลเวลรอบสุดท้าย'],
        ['การโจมตีร่วมให้ EXP 2–2.5 เท่า', 'เหลือมอนไว้ตัวเดียว ลดสถานะมัน แล้วปล่อยท่าไม้ตายพร้อมกันทั้งตัวเราและเพื่อน'],
        ['ธาตุไฟแรงที่สุดและตายง่ายที่สุด', 'ไฟเพิ่มพลังโจมตีที่ lv×2.0 ขณะที่ธาตุอื่นได้ 1.4 แต่รับดาเมจจากน้ำที่ ×0.5 และน้ำตีไฟที่ ×1.6 คือการข่มธาตุที่รุนแรงที่สุดในเกม'],
      ],
      trustTitle: 'เชื่อข้อมูลแต่ละแถวได้แค่ไหน',
      trustLede:
        'ทุกแถวมีป้ายระดับความน่าเชื่อถือกำกับไว้ ดูก่อนเสมอก่อนจะทุ่มหนังสือเล่มสูงหรืออัญมณีหายาก',
      sourceTitle: 'ข้อมูลนี้มาจากไหน',
      sourceBody:
        'เซิร์ฟไต้หวันเปิดเมื่อมิถุนายน 2025 และมีข้อมูลจากคอมมูนิตี้สะสมมาแล้วหนึ่งปีเต็ม ส่วนเซิร์ฟไทยเพิ่งเปิดกรกฎาคม 2026 ข้อมูลหลักของเว็บนี้จึงมาจากไต้หวัน — ตารางสูตรรวม 「星飄」 ที่รวบรวมโดย 苦茶 อัปเดตล่าสุด 30 พ.ค. 2026 และเทียบกับไคลเอนต์ไทยเท่าที่ทำได้ การจับคู่ชื่อใช้เลเวลไอเทมกับค่าสถานะเป็นหลัก ไม่ใช้ชื่ออย่างเดียว',
      warnTitle: 'สองอย่างที่เว็บนี้ไม่ใช่',
      warnBody:
        'นี่ไม่ใช่ข้อมูลสดจากเกม — ต้นฉบับหยุดอัปเดตที่ 30 พ.ค. 2026 และชื่อไทยทั้งหมดเป็นคำแปล ยกเว้นที่ระบุว่ายืนยันจากในเกมแล้ว ชื่อไทยที่หาไม่เจอในไคลเอนต์ของคุณแย่กว่าชื่ออังกฤษ ดังนั้นให้ดูเลเวลไอเทมกับค่าสถานะก่อนเสมอ',
    },
    compounds: {
      title: 'ฐานข้อมูลสูตรรวมไอเทม',
      lede:
        'สูตรรวมทั้งหมดจากตารางคอมมูนิตี้ไต้หวัน รวมตระกูลประกายดาวแล้ว กรองได้ตามตระกูลวัสดุ ประเภท เลเวลไอเทม หรือค่าสถานะ — “ดาบที่ ATK > 35” คือเลือกประเภทดาบ แล้วเพิ่มตัวกรองค่าสถานะหนึ่งอัน อ่านช่องสูตรเป็น “ตระกูลวัสดุ” ไม่ใช่ชื่อไอเทม — “18 Pure Iron + Wolf Fang” หมายถึงของตระกูลเหล็กแดงเลเวลไอเทม 18 ชิ้นไหนก็ได้ บวกเขี้ยวหมาป่า',
      verifiedOnly: 'เฉพาะที่ยืนยันแล้ว',
    },
    materials: {
      title: 'ร้านค้าและวัตถุดิบ',
      lede:
        'ร้านไหนขายวัสดุตระกูลไหน เลเวลไอเทมเท่าไหร่ ราคาเท่าไหร่ และเมืองนั้นเปิดบนเซิร์ฟไทยแล้วหรือยัง — ปิดตัวกรอง “เฉพาะที่มีขายในร้าน” เพื่อดูวัสดุอีก 74 ชิ้นที่ต้องดรอป เก็บ หรือคราฟเอง',
      openOnly: 'ซื้อได้จริงบนแมพไทยตอนนี้',
      openOnlyHelp:
        'แพตช์เดือน 9/2026 เปิดหมู่บ้านประมงจีน กรุงเทพฯ และมาดากัสการ์เพิ่ม รวมเป็นออสเตรเลีย เกาะอีสเตอร์ การ์กาตา แอนตาร์กติกา หมู่บ้านประมงจีน และกรุงเทพฯ ที่มีร้านขายของ ส่วนอียิปต์ (ซึ่งคือทั้งชั้นเลเวลไอเทม 18) ญี่ปุ่น เกาหลี ฉางอาน เอเธนส์ และเกาะวาฬยักษ์ ยังไม่เปิด',
      where: 'ร้านที่ขาย',
      price: 'ราคา',
      shopOnly: 'เฉพาะที่มีขายในร้าน',
      unknownSource: 'ยังไม่ทราบที่มา',
      noShop: 'ไม่มีร้านไหนขาย',
      shop: 'ร้านค้า',
      drop: 'มอนดรอป',
      gather: 'เก็บเอง',
      craft: 'เครื่องคราฟ',
      scroll: 'สกรอลล์เล่นแร่',
      cheapest: 'ถูกที่สุดในตระกูล',
      highest: 'ซื้อได้สูงสุด',
      key: 'วัสดุสำคัญ',
      priceLegacy: 'ราคาจากเกมเก่า อาจไม่ตรงกับ Re',
      priceRe: 'ราคายืนยันจากตาราง Re',
      closed: 'ยังไม่เปิดบนเซิร์ฟไทย',
      open: 'เปิดแล้วบนเซิร์ฟไทย',
      unverified: 'ไม่ทราบสถานะ',
      notInRe: 'ไม่มีอยู่ใน Re',
    },
    star: {
      title: 'ตระกูลประกายดาว',
      lede:
        'สายวัสดุ 星耀 / ประกายดาว ที่มีเฉพาะใน Re — ไม่มีในเกมเก่า และไต่ได้ลึกกว่าตระกูลอื่นทั้งหมด ถึงเลเวลไอเทม 60',
      pairNote:
        'ตระกูลนี้สร้างเป็นคู่ เกือบทุกเลเวลจะมีสองชิ้น: สายเวทที่จับคู่ประกายดาวกับวัสดุอ่อน และสายกายภาพที่จับคู่กับโลหะ เลเวลเท่ากัน ช่องเดียวกัน ค่าสถานะสลับกัน',
      all: 'ทั้งหมด',
      magic: 'สายเวท',
      phys: 'สายกายภาพ',
      mat: 'วัตถุดิบ',
      random: 'ค่าสถานะสุ่ม',
      bands: {
        'Dust tier — Star + Flower / Copper': 'ชั้นผงดาว — ประกายดาว + ดอกไม้ / ทองแดง',
        'Early — Star + Grass / Iron': 'ช่วงต้น — ประกายดาว + หญ้า / เหล็ก',
        'Mid — Star + Wood / Pure Iron, then the Stardust set': 'ช่วงกลาง — ประกายดาว + ไม้ / เหล็กแดง แล้วต่อด้วยเซ็ตฝุ่นดาว',
        'High — two secondaries per piece': 'ช่วงสูง — วัสดุรองสองชนิดต่อชิ้น',
        'Constellation & Firmament — three secondaries': 'สายหมู่ดาวและนภากาศ — วัสดุรองสามชนิด',
        'Endgame — four secondaries, random stats': 'เอนด์เกม — วัสดุรองสี่ชนิด ค่าสถานะสุ่ม',
      },
    },
    sim: {
      title: 'วางแผนการรวมไอเทม',
      lede:
        'สร้างแผนผังการรวมของคุณเอง ไอเทมที่อยากได้อยู่บนสุด แล้วเพิ่มสิ่งที่วางแผนจะเอามารวมไว้ข้างล่าง — ไอเทมอะไรก็ได้ วัตถุดิบอะไรก็ได้ หรือพิมพ์เองก็ได้ ลึกได้ถึง 20 ชั้น จากนั้นบันทึกเป็นรูปภาพแล้วทำตามขั้นตอนจากล่างขึ้นบน',
      caveat:
        'ไม่มีอะไรบังคับหรือแนะนำ นี่คือโน้ตของคุณเอง ปุ่ม ⇣ บนไอเทมจะดึงสูตรจากฐานข้อมูลมาให้เป็นจุดเริ่มต้น แก้หรือลบสิ่งที่มันเพิ่มมาได้ตามใจ',
      pickTarget: 'ค้นหาไอเทมที่อยากรวม…',
      pickAny: 'ค้นหาไอเทมหรือวัตถุดิบ…',
      freeText: 'หรือพิมพ์อะไรก็ได้',
      or: 'หรือ',
      emptyHint: 'เลือกไอเทมเป้าหมายด้านบนเพื่อเริ่มวางแผน',
      steps: 'ขั้นตอน',
      depth: 'ความลึก',
      stepsTitle: 'ลำดับการไต่ จากล่างขึ้นบน',
      stepsHelp: 'ทุกโหนดที่มีลูกจะกลายเป็นหนึ่งขั้นตอน ข้อความใน [วงเล็บ] มาจากช่องโน้ตของโหนดนั้น',
      expandHint: 'กด ＋ ใต้ไอเทมเป้าหมายเพื่อเพิ่มวัตถุดิบ',
      notePh: 'โน้ต… (×2, ซื้อที่อียิปต์)',
      addChild: 'เพิ่มวัตถุดิบข้างล่างนี้',
      loadRecipe: 'ดึงสูตรของไอเทมนี้จากฐานข้อมูล',
      remove: 'ลบ',
      savePng: 'บันทึกเป็นรูปภาพ',
      basketTitle: 'ลิสต์วางแผน',
      basketHelp: 'ติดดาวมาจากหน้าสูตรรวม เลือกโหนดในแผนผังก่อน แล้วกดเพิ่มไอเทมไว้ข้างใต้',
      basketEmpty: 'ยังไม่มีอะไรในลิสต์ — ติดดาว (☆) ไอเทมในหน้าสูตรรวมไอเทม',
      basketAsRoot: 'ตั้งเป็นเป้าหมาย',
      basketAddUnder: 'เพิ่มใต้',
      basketNoSel: 'เลือกโหนดก่อน',
      basketClear: 'ล้างลิสต์',
      selected: 'ที่เลือกอยู่',
      fit: 'พอดีจอ',
      zoomHint: 'เลื่อนล้อเมาส์เพื่อซูม · เลื่อนแถบเพื่อเลื่อนดู',
      newPlan: 'แผนใหม่',
      confirmNew: 'ล้างแผนนี้แล้วเริ่มใหม่?',
      material: 'วัตถุดิบ',
      book: 'หนังสือ',
      anyBook: 'หนังสือเล่นแร่ (เล่มไหนก็ได้)',
      where: 'ร้านที่ขาย',
      price: 'ราคา',
      shopOnly: 'เฉพาะที่มีขายในร้าน',
      unknownSource: 'ยังไม่ทราบที่มา',
      noShop: 'ไม่มีร้านไหนขาย',
      shop: 'ร้านค้า',
      open: 'เปิดแล้วบนเซิร์ฟไทย',
      closed: 'ยังไม่เปิดบนเซิร์ฟไทย',
    },
    glossary: {
      title: 'คำศัพท์',
      lede:
        'จีน ⇄ อังกฤษ ⇄ ไทย ข้อมูลค้นคว้าทั้งหมดเป็นภาษาจีนตัวเต็ม แต่ไคลเอนต์ของคุณเป็นภาษาไทย หน้านี้คือสะพานเชื่อม',
      sections: {
        system: 'คำศัพท์ระบบ',
        ui: 'หน้าจอไคลเอนต์ไทย',
        stats: 'ค่าสถานะและธาตุ',
        jobs: 'อาชีพและสถานะผิดปกติ',
        catalysts: 'วัสดุตัวเร่งสำคัญ',
      },
      confirmedNote: 'อ่านมาจากไคลเอนต์ไทยจริง',
    },
    quests: {
      title: 'เควส',
      lede: 'รายการเควสแยกตามหมวด ส่วนใหญ่ยังเป็นข้อมูลจาก WLO เวอร์ชันเก่า เพราะบอร์ดไต้หวันที่มีรายการของ Re ปิดกั้นการดึงข้อมูลอัตโนมัติ ให้ถือว่าแถวข้อมูลเก่าเป็นแนวทาง ไม่ใช่ข้อความจริงในเกมไทย',
      search: 'ค้นหาชื่อเควส NPC สถานที่ หรือของรางวัล…',
      allTypes: 'ทุกหมวดเควส',
      type: 'หมวด',
      quest: 'ชื่อเควส',
      where: 'สถานที่',
      req: 'เงื่อนไข',
      reward: 'รางวัล',
      stars: 'ดาว',
      detail: 'ขั้นตอน / หมายเหตุ',
      earn: 'ได้',
      spend: 'ใช้',
      reOnly: 'เฉพาะที่ยืนยันใน Re',
      source: 'แหล่งข้อมูล',
      sourceKinds: {
        wiki: 'วิกิ EN',
        cnwiki: 'วิกิ 中文',
        guide: 'คู่มือ',
        reguide: 'คู่มือ Re',
        index: 'ดัชนีเควส',
        baha: 'กระทู้ 巴哈',
        board: 'บอร์ด Re',
        search: 'ค้นหา',
      },
      sourceHelp: {
        wiki: 'วิกิ Fandom ของ Wonderland Online — หน้าเควส ส่วนใหญ่มีภาพประกอบ',
        cnwiki: 'สารานุกรมจีนของบอร์ดไต้หวัน สำหรับเกมเวอร์ชันแรก — วิธีทำละเอียดที่สุด',
        guide: 'คู่มือภาษาอังกฤษที่ครอบคลุมเควสนี้',
        reguide: 'เว็บคู่มือของ Re: Star Ark',
        index: 'ดัชนีเควสทั้งหมดของวิกิ Fandom แยกตามพื้นที่',
        baha: 'กระทู้บอร์ดไต้หวันที่เป็นที่มาของข้อมูลแถวนี้',
        board: 'บอร์ด Re: Star Ark บน 巴哈 — ค้นหาชื่อเควสนี้ในบอร์ด',
        search: 'ค้นหาชื่อเควสนี้ใน Google',
      },
      counts: '{n} จาก {total} เควส · ยืนยันใน Re แล้ว {re} รายการ',
      noResults: 'ไม่พบเควสที่ตรงกับตัวกรอง',
      gap: 'จุดที่ยังขาด: รายการเควสหลักและเควสรองฉบับเต็มของ Re ยังไม่มีเผยแพร่ที่ไหนที่เข้าถึงได้ ถ้าอ่านชื่อเควสจากในเกมได้ บอก KK แล้วจะเพิ่มให้',
    },
    footer: {
      source:
        'ที่มา: ตารางสูตรรวมของคอมมูนิตี้ Re 「星飄」 โดย 苦茶 และผู้ร่วมให้ข้อมูล อัปเดต 25 มิ.ย. 2025 → 30 พ.ค. 2026 ชื่อภาษาอังกฤษและไทยเป็นคำแปล ยกเว้นที่ระบุว่ายืนยันแล้ว',
      match: 'ให้จับคู่ไอเทมด้วยเลเวลไอเทมและค่าสถานะ ซึ่งไม่ขึ้นกับภาษา อย่าจับคู่ด้วยชื่อ',
      updated: 'ข้อมูล ณ วันที่',
    },
  },
};

export const t = (lang) => UI[lang] || UI[DEFAULT_LANG];
