// Interface strings. Thai first-class — every key must exist in both languages.
export const LANGS = ['th', 'en'];
export const DEFAULT_LANG = 'th';

export const UI = {
  en: {
    dir: 'ltr',
    site: {
      name: 'Star Drift',
      full: 'Wonderland Re: Star Ark — data',
      tagline:
        'The Taiwan-server compounding data for Wonderland Online Re: Star Ark, in English and Thai.',
    },
    view: { auto: 'Auto', mobile: 'Mobile', desktop: 'Desktop', viewHelp: 'Switch layout: auto / mobile / desktop' },
    nav: {
      compounds: 'Compounds',
      materials: 'Materials',
      simulator: 'Planner',
      quests: 'Quests',
      companions: 'Companions',
      feedback: 'Report',
      about: 'About',
      switchLang: 'ไทย',
    },
    common: {
      search: 'Search name, Chinese, recipe…',
      allFamilies: 'Any main family',
      allSecondaries: 'Any secondary family',
      mainFamily: 'Main structural family',
      secondFamily: 'Secondary family',
      allSlots: 'All slots',
      allTowns: 'All towns',
      rank: 'Rank',
      lv: 'Lv',
      item: 'Item',
      slot: 'Slot',
      families: 'Families',
      stats: 'Stats',
      recipe: 'Recipe',
      source: 'Where to get it',
      showing: '{n} of {total}',
      noResults: 'Nothing matches those filters.',
      reset: 'Reset',
      rankFrom: 'from',
      rankTo: 'to',
      untranslated: 'Thai name not yet confirmed',
      confirmedTh: 'Thai name confirmed in the live client',
      lvWarning: 'The source sheet’s equip level contradicts rank × 2 here',
      partialFamily: 'This family is only covered to rank 30 in the source',
      note: 'Note',
      legendKk: 'confirmed in the Thai client',
      legendDefault: 'no badge = reported by the community sheet',
      legendThOk: 'Thai name confirmed',
      legendThNo: 'Thai name still a translation',
      legendWarn: 'level and rank disagree in the source',
      statFilter: 'stat filter',
      stat: 'stat',
      value: 'value',
      sort: 'sort',
      sortDefault: 'by family',
      basket: 'Shortlist',
      addShort: 'Add',
      inBasket: 'Added',
      basketAdd: 'Add to the planner shortlist',
      basketRemove: 'Remove from the shortlist',
      basketHelp: 'Items you starred here appear in the planner, ready to drop into a tree',
      remove: 'remove',
      where: 'Sold at',
      price: 'Price',
      shopOnly: 'Sold in shops',
      unknownSource: 'source ?',
      noShop: 'Not sold in any shop',
      shop: 'Shop',
      allShops: 'All shops',
    },
    home: {
      eyebrow: 'Taiwan server data · Thai client',
      h1: 'Wonderland Re: Star Ark',
      lede:
        'A year of Taiwan-server research, translated. Compounding recipes, where every material comes from, and which shops you can actually reach on the Thai map.',
      cta: 'Open the compound database',
      statsTitle: 'What is in here',
      rulesTitle: 'Read this if you read nothing else',
      rules: [
        ['Compounding is the whole game.', 'Gear is crafted, not dropped. Compounded gear massively outclasses shop gear at the same level.'],
        ['Item rank = equip level ÷ 2.', 'Everything in crafting is about landing on an exact rank. The Thai client prints it as เลเวลไอเทม.'],
        ['The lowest-ranked ingredient sets the base.', 'Never mix a rank-25 gem with a rank-1 stick — you throw away the expensive one.'],
        ['Slot 1 chooses the result table.', 'The [หลัก] primary family decides what you can make. Order matters.'],
        ['Encyclopedia Vol. 1–4 go last.', 'They add +1…+4 rank and success rate, and they are the expensive part of any recipe.'],
        ['Primary alchemy to wash, Superior to finish.', 'Convert materials cheaply at low rank; save Superior for the final climb.'],
        ['Combo attack gives 2–2.5× EXP.', 'Leave one monster, debuff it, then player and companion both ultimate.'],
        ['Fire hits hardest and folds fastest.', 'Fire grows ATK at lv×2.0 against everyone else’s 1.4, but takes ×0.5 from water. Water→Fire at ×1.6 is the hardest counter in the game.'],
      ],
      trustTitle: 'How much to trust a row',
      trustLede:
        'Every row carries a confidence tag. Check it before you spend an Encyclopedia volume or a rare gem.',
      sourceTitle: 'Where this comes from',
      sourceBody:
        'The Taiwan server launched in June 2025 and has a year of community research behind it; the Thai server opened in July 2026. So the source of truth here is Taiwanese: the 「星飄」 community compounding sheet compiled by 苦茶, maintained to 2026-05-30, cross-checked against the Thai client wherever possible. Names are matched by rank and stat profile, never by name alone.',
      warnTitle: 'Two things this site is not',
      warnBody:
        'It is not a live mirror of the game — the source data stops at 2026-05-30. And Thai item names are translations unless marked as confirmed in the client. A Thai name you cannot find in your own client is worse than an English one, so check the rank and the stats first.',
    },
    compounds: {
      title: 'Compound database',
      lede:
        'Every compounding recipe from the Taiwan community sheet, Star family included. Filter by family, slot, rank, or stat — “sword with ATK > 35” is a slot plus one stat filter. Read the recipe column as material families, not item names — “18 Pure Iron + Wolf Fang” means any rank-18 Pure Iron item plus a Wolf Fang.',
      verifiedOnly: 'Verified only',
    },
    materials: {
      title: 'Shops & materials',
      lede:
        'Which shop sells which material, at what rank and price, and whether that town is open on the Thai server yet. Turn off “Sold in shops” to see the other 74 materials you have to drop, gather or craft.',
      openOnly: 'Buyable on the Thai map today',
      openOnlyHelp:
        'The September 2026 patch added China Fishing Village, Bangkok and Madagascar. Shop towns open on the Thai server now: Australia, Easter Island, Calcutta, Antarctica, China Fishing Village and Bangkok. Egypt — the whole rank-18 tier — Japan, Korea, Chang\u2019an, Athens and Whale Island are still closed.',
      where: 'Sold at',
      price: 'Price',
      shopOnly: 'Sold in shops',
      unknownSource: 'source ?',
      noShop: 'Not sold in any shop',
      shop: 'Shop',
      drop: 'Drop',
      gather: 'Gather',
      craft: 'Craft',
      scroll: 'Alchemy scroll',
      cheapest: 'Cheapest of family',
      highest: 'Highest buyable',
      key: 'Key material',
      priceLegacy: 'price is legacy data, may be wrong in Re',
      priceRe: 'price confirmed in the Re sheet',
      closed: 'closed on TH',
      open: 'open on TH',
      unverified: 'status unknown',
      notInRe: 'does not exist in Re',
    },
    star: {
      title: 'The Star family',
      lede:
        'The Re-exclusive 星耀 / ประกายดาว line — it does not exist in the original Wonderland Online, and it runs deeper than any other family, to rank 60.',
      pairNote:
        'The family is built in pairs. At almost every rank there are two items: a magic piece pairing Star with a soft family, and a physical piece pairing Star with a metal. Same rank, same slot, mirrored stats.',
      all: 'All',
      magic: 'Magic',
      phys: 'Physical',
      mat: 'Materials',
      random: 'stats roll randomly',
      bands: {
        'Dust tier — Star + Flower / Copper': 'Dust tier — Star + Flower / Copper',
        'Early — Star + Grass / Iron': 'Early — Star + Grass / Iron',
        'Mid — Star + Wood / Pure Iron, then the Stardust set': 'Mid — Star + Wood / Pure Iron, then the Stardust set',
        'High — two secondaries per piece': 'High — two secondaries per piece',
        'Constellation & Firmament — three secondaries': 'Constellation & Firmament — three secondaries',
        'Endgame — four secondaries, random stats': 'Endgame — four secondaries, random stats',
      },
    },
    sim: {
      title: 'Compound planner',
      lede:
        'Build your own compounding tree. The item you want sits at the top; add whatever you plan to combine beneath it — any item, any material, or your own text — as deep as 20 levels. Then save it as a picture and follow the steps from the bottom up.',
      caveat:
        'Nothing here is enforced or suggested. It is your note. The ⇣ button on an item pulls that item’s recipe from the database as a starting point; edit or delete anything it adds.',
      pickTarget: 'Search for the item you want to make…',
      pickAny: 'Search item or material…',
      freeText: 'or type anything',
      or: 'or',
      emptyHint: 'Choose a target item above to start a plan.',
      steps: 'steps',
      depth: 'depth',
      stepsTitle: 'The climb, bottom up',
      stepsHelp: 'Every node with children becomes a step. Notes in [brackets] come from the node’s note field.',
      expandHint: 'Add children under the target (＋) to get steps.',
      notePh: 'note… (×2, buy at Egypt)',
      addChild: 'Add an ingredient beneath this',
      loadRecipe: 'Load this item’s recipe from the database',
      remove: 'Remove',
      savePng: 'Save as picture',
      basketTitle: 'Shortlist',
      basketHelp: 'Starred on the compound page. Select a node in the tree, then add an item beneath it.',
      basketEmpty: 'Nothing here yet — star items (☆) on the compound page.',
      basketAsRoot: 'Use as target',
      basketAddUnder: 'Add under',
      basketNoSel: 'select a node first',
      basketClear: 'Clear shortlist',
      selected: 'selected',
      fit: 'Fit',
      zoomHint: 'scroll to zoom · drag scrollbars to pan',
      newPlan: 'New plan',
      confirmNew: 'Clear this plan and start over?',
      material: 'Material',
      book: 'Book',
      anyBook: 'Encyclopedia (any Vol.)',
      where: 'Sold at',
      price: 'Price',
      shopOnly: 'Sold in shops',
      unknownSource: 'source ?',
      noShop: 'Not sold in any shop',
      shop: 'Shop',
      open: 'open on TH',
      closed: 'closed on TH',
    },
    glossary: {
      title: 'Glossary',
      lede:
        'Chinese ⇄ English ⇄ Thai. The research is all in Traditional Chinese and your client is in Thai — this is the bridge.',
      sections: {
        system: 'System terms',
        ui: 'Thai client interface',
        stats: 'Stats and elements',
        jobs: 'Jobs and status effects',
        catalysts: 'Key catalysts',
      },
      confirmedNote: 'Read off the live Thai client',
    },
    quests: {
      title: 'Quests',
      lede: 'Quest lists by category. Most rows are still Legacy WLO data — the Taiwan board that holds the current Re lists blocks automated reading, so treat a legacy row as a strong hint, not as the Thai client\u2019s text.',
      search: 'Search quest, NPC, place, reward…',
      allTypes: 'All quest types',
      type: 'Type',
      quest: 'Quest',
      where: 'Where',
      req: 'Requirement',
      reward: 'Reward',
      stars: 'Stars',
      detail: 'Steps / notes',
      earn: 'earns',
      spend: 'costs',
      reOnly: 'Re-confirmed only',
      source: 'source',
      sourceKinds: {
        wiki: 'EN wiki',
        cnwiki: '中文 wiki',
        guide: 'Guide',
        reguide: 'Re guide',
        index: 'Quest index',
        baha: '巴哈 thread',
        board: 'Re board',
        search: 'Search',
      },
      sourceHelp: {
        wiki: 'Wonderland Online Fandom wiki — the quest page, usually with screenshots',
        cnwiki: 'Bahamut\u2019s Chinese encyclopedia for the original release — the most detailed walkthroughs',
        guide: 'An English walkthrough covering this quest',
        reguide: 'A Re: Star Ark guide site',
        index: 'Fandom\u2019s master quest index, by area',
        baha: 'The Taiwan board thread this row came from',
        board: 'The Re: Star Ark board on Bahamut — search it for this quest',
        search: 'Google search for this quest name',
      },
      counts: '{n} of {total} quests · {re} confirmed for Re',
      noResults: 'No quest matches those filters.',
      gap: 'Known gap: the full Re main-quest and side-quest lists are not published anywhere reachable. If you can read a quest name off your client, tell KK and it gets added.',
    },
    feedback: {
      title: 'Report wrong data',
      lede: 'Everything here comes from Taiwan-server research and has not been checked in the Thai client. If a row does not match your game, say so — that is the only way it gets fixed.',
      how: [
        'The exact name your client shows, spelled its way.',
        'A screenshot if you have one. It settles anything.',
        'What the site says, and what the game says.',
      ],
      notReady: 'The form is not connected yet — send corrections to KK directly for now.',
      openNew: 'Trouble with the form? Open it in a new tab',
      after: 'Confirmed reports are marked “Tested in-game”, the highest trust level on this site.',
    },
    companions: {
      title: 'Companion Rebirth & Exclusive Weapons',
      lede: 'Almost every companion has an exclusive item no other companion can equip, and Rebirth (轉生) upgrades that item while unlocking a new skill. What matters most here is the stat-floor mechanic — get it wrong and it is permanent.',
      dataNote: 'From the Taiwan server (星飄), roughly a year ahead of Thailand. Chinese names are kept beside every item so you can follow TW guides directly. Thai names are translations and unconfirmed — except ลิงคส์, which is the name in the Thai promo.',
      howTitle: 'How rebirth works',
      howReq: ['Companion at level 100 or above', 'Complete that companion\u2019s exclusive quest', 'Talk to the designated NPC (能者)', 'Clear the trial (試煉)'],
      howPill: 'Mall and event companions use a Rebirth Pill (轉生丹) instead.',
      howUnknown: 'Unknown: the designated NPC\u2019s name, and what the trial actually consists of. No public source documents either — check in client.',
      gainTitle: 'What you get',
      gain: ['A completely new appearance', 'One new rebirth skill', 'An upgraded exclusive weapon', 'Higher overall stats'],
      floorTitle: 'The stat-floor mechanic — read before rebirthing',
      floorIntro: 'Rebirth re-rolls the companion\u2019s stats at random (轉生點數 — 130 points for mall companions, 126–129 for quest companions). Each companion has published floors.',
      floorRuleUp: 'A stat that rolls ABOVE its floor can be washed (洗) freely, forever.',
      floorRuleDown: 'A stat that rolls BELOW its floor can never be washed again — not after pills, not after levelling into range.',
      floorExample: 'Mary I\u2019s WIS floor is 41. Roll 39 and WIS is permanently unwashable, even if pills later push it past 41.',
      floorSafe: ['Max your stat pills before rebirthing, or', 'Aim the roll so every stat clears its floor — after that you can re-wash as often as you like', 'Recommended: wash once at level 20, and again just before rebirth'],
      floorPills: 'Add +48 to these if the companion was pill-capped before rebirthing.',
      floorsHead: 'Known floors',
      gradeTitle: 'Three grades of exclusive gear',
      grades: [
        ['Base exclusive (專屬裝備)', 'held from recruitment', '—'],
        ['Rebirth exclusive (轉生專屬裝備)', 'the rebirth reward', 'Item rank 1 and indestructible — permanent, never needs repair'],
        ['Mall exclusive (商城專屬裝備)', 'cash shop', '“Golden” weapons, far higher raw stats — roughly 3× a rebirth weapon'],
      ],
      terminology: 'Humanoid companions equip arm-rings (臂環) and brooches (胸針); beast companions equip collars (項圈) and saddles (馬鞍).',
      pattern: 'Mall-companion rebirth weapons are formulaic: +50 to the primary stat.',
      thTitle: 'Thai server status',
      thStatus: [
        'Lynx is on TH — given away as the “Lynx Bag” in the daily top-up promotion, 26 Aug – 2 Sep 2026.',
        'Player job change at level 100 is live since 9 Sep 2026; the character drops to level 1. This is a different system from companion rebirth.',
        'Companion rebirth has no official TH announcement — but the mall already sells “Rebirth Ashin Bag” and “Rebirth Pearl Girl Bag”, so rebirth content is at least partly shipped. Check in client.',
        'TW opened rebirth on 31 Jul 2025 alongside the Bangkok map, in the same patch that introduced Lynx. TH already has Bangkok, so it should be close.',
      ],
      companion: 'Companion',
      kind: 'Type',
      pts: 'Points',
      exclusive: 'Exclusive',
      rebirthExclusive: 'Rebirth exclusive',
      rebirthSkill: 'Rebirth skill',
      questGroup: 'Quest companions',
      mallGroup: 'Mall / event companions — all 130 points, all via Rebirth Pill',
      types: { phys: 'physical', magic: 'magic', hybrid: 'phys + magic', gun: 'gun', bow: 'bow' },
      forms: { human: 'humanoid', beast: 'beast' },
      spotlight: 'In focus',
      skills: 'Skills',
      skillsHint: 'Click a companion’s name to read its skills',
      skillOpen: 'skills',
      skillSp: 'SP',
      skillMaxShort: 'max',
      skillUpgrade: 'upgrades to',
      skillRebirth: 'rebirth skill',
      skillLegacy: 'SP, target and description are from WLOHUB’s legacy-game data, not Re',
      skillLegacyMark: 'legacy',
      skillSourceNote: 'Skill names and max levels come from the Re compendium (星飄) and cover all 25 companions. SP cost, target pattern and descriptions come from WLOHUB, which only documents the legacy game — 12 companions have them, and those numbers are pre-Re. Thai skill names are translations.',
      ways: {
        near: 'Near attack',
        dist: 'Distance',
        aid: 'Aid skill',
        buff: 'Stat buff',
        single: 'Single target',
      },
      maxLv: 'Max Lv',
      otherGear: 'Other gear',
      slots: {
        blade: 'Weapon · blade',
        sword: 'Weapon · sword',
        wand: 'Weapon · wand',
        club: 'Weapon · club',
        gun: 'Weapon · gun',
        bow: 'Weapon · bow',
        claw: 'Weapon · claw',
        weapon: 'Weapon',
        accessory: 'Accessory',
        head: 'Head',
        hand: 'Hand / arm',
      },
      slotLabel: 'Slot',
      slotInferred: 'inferred',
      slotInferredHelp: 'No source states the slot. Inferred from the item having no slot tag in the compendium, which in that sheet means a weapon.',
      slotConfirmedHelp: 'Slot stated by a source (WLOHUB item page or the compendium slot tag)',
      slotConflict: 'Sources disagree — see note',
      slotNoteHead: 'Slot note',
      slotLegend: 'Every exclusive item shows the slot it goes in. A slot marked “inferred” is not stated by any source — it comes from the compendium convention that an exclusive with no slot tag is a weapon. 28 of the 49 items are source-stated; the rest are inferred. WLOHUB has no pages at all for the 12 mall/Re-original companions.',
      counts: '{n} companions · {quest} from quests, {mall} from the mall',
    },
    footer: {
      source:
        'Source: the Re community compounding sheet 「星飄」 by 苦茶 and named contributors, maintained 2025-06-25 → 2026-05-30. English and Thai names are translations unless marked confirmed.',
      match: 'Match items by rank and stats, which are language-independent — not by name.',
      updated: 'Data as of',
    },
  },

  th: {
    dir: 'ltr',
    site: {
      name: 'Star Drift',
      full: 'Wonderland Re: Star Ark — ฐานข้อมูล',
      tagline:
        'ข้อมูลการรวมไอเทมจากเซิร์ฟไต้หวันของ Wonderland Online Re: Star Ark ทั้งภาษาไทยและอังกฤษ',
    },
    view: { auto: 'อัตโนมัติ', mobile: 'มือถือ', desktop: 'จอใหญ่', viewHelp: 'สลับเลย์เอาต์: อัตโนมัติ / มือถือ / จอใหญ่' },
    nav: {
      compounds: 'สูตรรวมไอเทม',
      materials: 'ร้านค้า',
      simulator: 'วางแผนการรวม',
      quests: 'เควส',
      companions: 'ขุนพล',
      feedback: 'แจ้งข้อมูล',
      about: 'เกี่ยวกับ',
      switchLang: 'EN',
    },
    common: {
      search: 'ค้นหาชื่อ ภาษาจีน หรือสูตร…',
      allFamilies: 'ทุกตระกูลหลัก',
      allSecondaries: 'ทุกตระกูลรอง',
      mainFamily: 'ตระกูลวัสดุหลัก',
      secondFamily: 'ตระกูลวัสดุรอง',
      allSlots: 'ทุกช่องสวมใส่',
      allTowns: 'ทุกเมือง',
      rank: 'เลเวลไอเทม',
      lv: 'ลิมิต',
      item: 'ไอเทม',
      slot: 'ประเภท',
      families: 'วัสดุโครงสร้าง',
      stats: 'ค่าสถานะ',
      recipe: 'สูตร',
      source: 'หาได้จากที่ไหน',
      showing: '{n} จาก {total}',
      noResults: 'ไม่พบรายการที่ตรงกับตัวกรอง',
      reset: 'ล้างตัวกรอง',
      rankFrom: 'ตั้งแต่',
      rankTo: 'ถึง',
      untranslated: 'ยังไม่ยืนยันชื่อไทย',
      confirmedTh: 'ยืนยันชื่อไทยจากในเกมแล้ว',
      lvWarning: 'ลิมิตเลเวลในต้นฉบับไม่ตรงกับ เลเวลไอเทม × 2',
      partialFamily: 'ต้นฉบับมีข้อมูลตระกูลนี้ถึงเลเวลไอเทม 30 เท่านั้น',
      note: 'หมายเหตุ',
      legendKk: 'ยืนยันในไคลเอนต์ไทยแล้ว',
      legendDefault: 'ไม่มีป้าย = ข้อมูลจากตารางคอมมูนิตี้',
      legendThOk: 'ยืนยันชื่อไทยแล้ว',
      legendThNo: 'ชื่อไทยยังเป็นคำแปล',
      legendWarn: 'ลิมิตเลเวลกับเลเวลไอเทมในต้นฉบับไม่ตรงกัน',
      statFilter: 'กรองค่าสถานะ',
      stat: 'ค่าสถานะ',
      value: 'ค่า',
      sort: 'เรียงลำดับ',
      sortDefault: 'ตามตระกูล',
      basket: 'ลิสต์วางแผน',
      addShort: 'เพิ่ม',
      inBasket: 'อยู่ในลิสต์',
      basketAdd: 'เพิ่มเข้าลิสต์วางแผน',
      basketRemove: 'เอาออกจากลิสต์',
      basketHelp: 'ไอเทมที่ติดดาวไว้จะไปรอในหน้าวางแผน พร้อมลากเข้าแผนผัง',
      remove: 'ลบ',
      where: 'ร้านที่ขาย',
      price: 'ราคา',
      shopOnly: 'เฉพาะที่มีขายในร้าน',
      unknownSource: 'ยังไม่ทราบที่มา',
      noShop: 'ไม่มีร้านไหนขาย',
      shop: 'ร้านค้า',
      allShops: 'ทุกร้านค้า',
    },
    home: {
      eyebrow: 'ข้อมูลเซิร์ฟไต้หวัน · สำหรับไคลเอนต์ไทย',
      h1: 'Wonderland Re: Star Ark',
      lede:
        'งานค้นคว้าจากเซิร์ฟไต้หวันตลอดหนึ่งปี แปลไว้ให้แล้ว — สูตรรวมไอเทม แหล่งที่มาของวัตถุดิบทุกชิ้น และร้านไหนที่เปิดให้ซื้อได้จริงบนแมพไทย',
      cta: 'เปิดฐานข้อมูลสูตรรวม',
      statsTitle: 'ในนี้มีอะไรบ้าง',
      rulesTitle: 'ถ้าจะอ่านแค่อย่างเดียว อ่านตรงนี้',
      rules: [
        ['การรวมไอเทมคือหัวใจของเกม', 'อุปกรณ์ได้จากการรวม ไม่ใช่ดรอป ของที่รวมเองแรงกว่าของร้านที่เลเวลเดียวกันมาก'],
        ['เลเวลไอเทม = ลิมิตเลเวล ÷ 2', 'ทุกอย่างในการคราฟคือการทำให้ได้เลเวลไอเทมที่ต้องการพอดี ไคลเอนต์ไทยแสดงค่านี้ตรง ๆ ในชื่อ เลเวลไอเทม'],
        ['วัตถุดิบที่เลเวลต่ำสุดเป็นตัวกำหนดฐาน', 'อย่าเอาอัญมณีเลเวล 25 ไปรวมกับไม้เลเวล 1 เพราะของแพงจะเสียเปล่า'],
        ['ช่องที่ 1 เป็นตัวเลือกตารางผลลัพธ์', 'วัสดุที่ติดป้าย [หลัก] เป็นตัวกำหนดว่าจะรวมออกมาเป็นอะไร ลำดับการใส่จึงสำคัญ'],
        ['หนังสือเล่ม 1–4 ใส่เป็นอันสุดท้ายเสมอ', 'เพิ่มเลเวลไอเทม +1…+4 และเพิ่มโอกาสสำเร็จ และเป็นส่วนที่แพงที่สุดของทุกสูตร'],
        ['ขั้นต้นไว้ล้างวัสดุ ขั้นสูงไว้ปิดจ็อบ', 'ใช้วิชาขั้นต้นแปลงวัสดุที่เลเวลต่ำ ๆ เพราะถูก แล้วเก็บวิชาขั้นสูงไว้ไต่เลเวลรอบสุดท้าย'],
        ['การโจมตีร่วมให้ EXP 2–2.5 เท่า', 'เหลือมอนไว้ตัวเดียว ลดสถานะมัน แล้วปล่อยท่าไม้ตายพร้อมกันทั้งตัวเราและเพื่อน'],
        ['ธาตุไฟแรงที่สุดและตายง่ายที่สุด', 'ไฟเพิ่มพลังโจมตีที่ lv×2.0 ขณะที่ธาตุอื่นได้ 1.4 แต่รับดาเมจจากน้ำที่ ×0.5 และน้ำตีไฟที่ ×1.6 คือการข่มธาตุที่รุนแรงที่สุดในเกม'],
      ],
      trustTitle: 'เชื่อข้อมูลแต่ละแถวได้แค่ไหน',
      trustLede:
        'ทุกแถวมีป้ายระดับความน่าเชื่อถือกำกับไว้ ดูก่อนเสมอก่อนจะทุ่มหนังสือเล่มสูงหรืออัญมณีหายาก',
      sourceTitle: 'ข้อมูลนี้มาจากไหน',
      sourceBody:
        'เซิร์ฟไต้หวันเปิดเมื่อมิถุนายน 2025 และมีข้อมูลจากคอมมูนิตี้สะสมมาแล้วหนึ่งปีเต็ม ส่วนเซิร์ฟไทยเพิ่งเปิดกรกฎาคม 2026 ข้อมูลหลักของเว็บนี้จึงมาจากไต้หวัน — ตารางสูตรรวม 「星飄」 ที่รวบรวมโดย 苦茶 อัปเดตล่าสุด 30 พ.ค. 2026 และเทียบกับไคลเอนต์ไทยเท่าที่ทำได้ การจับคู่ชื่อใช้เลเวลไอเทมกับค่าสถานะเป็นหลัก ไม่ใช้ชื่ออย่างเดียว',
      warnTitle: 'สองอย่างที่เว็บนี้ไม่ใช่',
      warnBody:
        'นี่ไม่ใช่ข้อมูลสดจากเกม — ต้นฉบับหยุดอัปเดตที่ 30 พ.ค. 2026 และชื่อไทยทั้งหมดเป็นคำแปล ยกเว้นที่ระบุว่ายืนยันจากในเกมแล้ว ชื่อไทยที่หาไม่เจอในไคลเอนต์ของคุณแย่กว่าชื่ออังกฤษ ดังนั้นให้ดูเลเวลไอเทมกับค่าสถานะก่อนเสมอ',
    },
    compounds: {
      title: 'ฐานข้อมูลสูตรรวมไอเทม',
      lede:
        'สูตรรวมทั้งหมดจากตารางคอมมูนิตี้ไต้หวัน รวมตระกูลประกายดาวแล้ว กรองได้ตามตระกูลวัสดุ ประเภท เลเวลไอเทม หรือค่าสถานะ — “ดาบที่ ATK > 35” คือเลือกประเภทดาบ แล้วเพิ่มตัวกรองค่าสถานะหนึ่งอัน อ่านช่องสูตรเป็น “ตระกูลวัสดุ” ไม่ใช่ชื่อไอเทม — “18 Pure Iron + Wolf Fang” หมายถึงของตระกูลเหล็กแดงเลเวลไอเทม 18 ชิ้นไหนก็ได้ บวกเขี้ยวหมาป่า',
      verifiedOnly: 'เฉพาะที่ยืนยันแล้ว',
    },
    materials: {
      title: 'ร้านค้าและวัตถุดิบ',
      lede:
        'ร้านไหนขายวัสดุตระกูลไหน เลเวลไอเทมเท่าไหร่ ราคาเท่าไหร่ และเมืองนั้นเปิดบนเซิร์ฟไทยแล้วหรือยัง — ปิดตัวกรอง “เฉพาะที่มีขายในร้าน” เพื่อดูวัสดุอีก 74 ชิ้นที่ต้องดรอป เก็บ หรือคราฟเอง',
      openOnly: 'ซื้อได้จริงบนแมพไทยตอนนี้',
      openOnlyHelp:
        'แพตช์เดือน 9/2026 เปิดหมู่บ้านประมงจีน กรุงเทพฯ และมาดากัสการ์เพิ่ม รวมเป็นออสเตรเลีย เกาะอีสเตอร์ การ์กาตา แอนตาร์กติกา หมู่บ้านประมงจีน และกรุงเทพฯ ที่มีร้านขายของ ส่วนอียิปต์ (ซึ่งคือทั้งชั้นเลเวลไอเทม 18) ญี่ปุ่น เกาหลี ฉางอาน เอเธนส์ และเกาะวาฬยักษ์ ยังไม่เปิด',
      where: 'ร้านที่ขาย',
      price: 'ราคา',
      shopOnly: 'เฉพาะที่มีขายในร้าน',
      unknownSource: 'ยังไม่ทราบที่มา',
      noShop: 'ไม่มีร้านไหนขาย',
      shop: 'ร้านค้า',
      drop: 'มอนดรอป',
      gather: 'เก็บเอง',
      craft: 'เครื่องคราฟ',
      scroll: 'สกรอลล์เล่นแร่',
      cheapest: 'ถูกที่สุดในตระกูล',
      highest: 'ซื้อได้สูงสุด',
      key: 'วัสดุสำคัญ',
      priceLegacy: 'ราคาจากเกมเก่า อาจไม่ตรงกับ Re',
      priceRe: 'ราคายืนยันจากตาราง Re',
      closed: 'ยังไม่เปิดบนเซิร์ฟไทย',
      open: 'เปิดแล้วบนเซิร์ฟไทย',
      unverified: 'ไม่ทราบสถานะ',
      notInRe: 'ไม่มีอยู่ใน Re',
    },
    star: {
      title: 'ตระกูลประกายดาว',
      lede:
        'สายวัสดุ 星耀 / ประกายดาว ที่มีเฉพาะใน Re — ไม่มีในเกมเก่า และไต่ได้ลึกกว่าตระกูลอื่นทั้งหมด ถึงเลเวลไอเทม 60',
      pairNote:
        'ตระกูลนี้สร้างเป็นคู่ เกือบทุกเลเวลจะมีสองชิ้น: สายเวทที่จับคู่ประกายดาวกับวัสดุอ่อน และสายกายภาพที่จับคู่กับโลหะ เลเวลเท่ากัน ช่องเดียวกัน ค่าสถานะสลับกัน',
      all: 'ทั้งหมด',
      magic: 'สายเวท',
      phys: 'สายกายภาพ',
      mat: 'วัตถุดิบ',
      random: 'ค่าสถานะสุ่ม',
      bands: {
        'Dust tier — Star + Flower / Copper': 'ชั้นผงดาว — ประกายดาว + ดอกไม้ / ทองแดง',
        'Early — Star + Grass / Iron': 'ช่วงต้น — ประกายดาว + หญ้า / เหล็ก',
        'Mid — Star + Wood / Pure Iron, then the Stardust set': 'ช่วงกลาง — ประกายดาว + ไม้ / เหล็กแดง แล้วต่อด้วยเซ็ตฝุ่นดาว',
        'High — two secondaries per piece': 'ช่วงสูง — วัสดุรองสองชนิดต่อชิ้น',
        'Constellation & Firmament — three secondaries': 'สายหมู่ดาวและนภากาศ — วัสดุรองสามชนิด',
        'Endgame — four secondaries, random stats': 'เอนด์เกม — วัสดุรองสี่ชนิด ค่าสถานะสุ่ม',
      },
    },
    sim: {
      title: 'วางแผนการรวมไอเทม',
      lede:
        'สร้างแผนผังการรวมของคุณเอง ไอเทมที่อยากได้อยู่บนสุด แล้วเพิ่มสิ่งที่วางแผนจะเอามารวมไว้ข้างล่าง — ไอเทมอะไรก็ได้ วัตถุดิบอะไรก็ได้ หรือพิมพ์เองก็ได้ ลึกได้ถึง 20 ชั้น จากนั้นบันทึกเป็นรูปภาพแล้วทำตามขั้นตอนจากล่างขึ้นบน',
      caveat:
        'ไม่มีอะไรบังคับหรือแนะนำ นี่คือโน้ตของคุณเอง ปุ่ม ⇣ บนไอเทมจะดึงสูตรจากฐานข้อมูลมาให้เป็นจุดเริ่มต้น แก้หรือลบสิ่งที่มันเพิ่มมาได้ตามใจ',
      pickTarget: 'ค้นหาไอเทมที่อยากรวม…',
      pickAny: 'ค้นหาไอเทมหรือวัตถุดิบ…',
      freeText: 'หรือพิมพ์อะไรก็ได้',
      or: 'หรือ',
      emptyHint: 'เลือกไอเทมเป้าหมายด้านบนเพื่อเริ่มวางแผน',
      steps: 'ขั้นตอน',
      depth: 'ความลึก',
      stepsTitle: 'ลำดับการไต่ จากล่างขึ้นบน',
      stepsHelp: 'ทุกโหนดที่มีลูกจะกลายเป็นหนึ่งขั้นตอน ข้อความใน [วงเล็บ] มาจากช่องโน้ตของโหนดนั้น',
      expandHint: 'กด ＋ ใต้ไอเทมเป้าหมายเพื่อเพิ่มวัตถุดิบ',
      notePh: 'โน้ต… (×2, ซื้อที่อียิปต์)',
      addChild: 'เพิ่มวัตถุดิบข้างล่างนี้',
      loadRecipe: 'ดึงสูตรของไอเทมนี้จากฐานข้อมูล',
      remove: 'ลบ',
      savePng: 'บันทึกเป็นรูปภาพ',
      basketTitle: 'ลิสต์วางแผน',
      basketHelp: 'ติดดาวมาจากหน้าสูตรรวม เลือกโหนดในแผนผังก่อน แล้วกดเพิ่มไอเทมไว้ข้างใต้',
      basketEmpty: 'ยังไม่มีอะไรในลิสต์ — ติดดาว (☆) ไอเทมในหน้าสูตรรวมไอเทม',
      basketAsRoot: 'ตั้งเป็นเป้าหมาย',
      basketAddUnder: 'เพิ่มใต้',
      basketNoSel: 'เลือกโหนดก่อน',
      basketClear: 'ล้างลิสต์',
      selected: 'ที่เลือกอยู่',
      fit: 'พอดีจอ',
      zoomHint: 'เลื่อนล้อเมาส์เพื่อซูม · เลื่อนแถบเพื่อเลื่อนดู',
      newPlan: 'แผนใหม่',
      confirmNew: 'ล้างแผนนี้แล้วเริ่มใหม่?',
      material: 'วัตถุดิบ',
      book: 'หนังสือ',
      anyBook: 'หนังสือเล่นแร่ (เล่มไหนก็ได้)',
      where: 'ร้านที่ขาย',
      price: 'ราคา',
      shopOnly: 'เฉพาะที่มีขายในร้าน',
      unknownSource: 'ยังไม่ทราบที่มา',
      noShop: 'ไม่มีร้านไหนขาย',
      shop: 'ร้านค้า',
      open: 'เปิดแล้วบนเซิร์ฟไทย',
      closed: 'ยังไม่เปิดบนเซิร์ฟไทย',
    },
    glossary: {
      title: 'คำศัพท์',
      lede:
        'จีน ⇄ อังกฤษ ⇄ ไทย ข้อมูลค้นคว้าทั้งหมดเป็นภาษาจีนตัวเต็ม แต่ไคลเอนต์ของคุณเป็นภาษาไทย หน้านี้คือสะพานเชื่อม',
      sections: {
        system: 'คำศัพท์ระบบ',
        ui: 'หน้าจอไคลเอนต์ไทย',
        stats: 'ค่าสถานะและธาตุ',
        jobs: 'อาชีพและสถานะผิดปกติ',
        catalysts: 'วัสดุตัวเร่งสำคัญ',
      },
      confirmedNote: 'อ่านมาจากไคลเอนต์ไทยจริง',
    },
    quests: {
      title: 'เควส',
      lede: 'รายการเควสแยกตามหมวด ส่วนใหญ่ยังเป็นข้อมูลจาก WLO เวอร์ชันเก่า เพราะบอร์ดไต้หวันที่มีรายการของ Re ปิดกั้นการดึงข้อมูลอัตโนมัติ ให้ถือว่าแถวข้อมูลเก่าเป็นแนวทาง ไม่ใช่ข้อความจริงในเกมไทย',
      search: 'ค้นหาชื่อเควส NPC สถานที่ หรือของรางวัล…',
      allTypes: 'ทุกหมวดเควส',
      type: 'หมวด',
      quest: 'ชื่อเควส',
      where: 'สถานที่',
      req: 'เงื่อนไข',
      reward: 'รางวัล',
      stars: 'ดาว',
      detail: 'ขั้นตอน / หมายเหตุ',
      earn: 'ได้',
      spend: 'ใช้',
      reOnly: 'เฉพาะที่ยืนยันใน Re',
      source: 'แหล่งข้อมูล',
      sourceKinds: {
        wiki: 'วิกิ EN',
        cnwiki: 'วิกิ 中文',
        guide: 'คู่มือ',
        reguide: 'คู่มือ Re',
        index: 'ดัชนีเควส',
        baha: 'กระทู้ 巴哈',
        board: 'บอร์ด Re',
        search: 'ค้นหา',
      },
      sourceHelp: {
        wiki: 'วิกิ Fandom ของ Wonderland Online — หน้าเควส ส่วนใหญ่มีภาพประกอบ',
        cnwiki: 'สารานุกรมจีนของบอร์ดไต้หวัน สำหรับเกมเวอร์ชันแรก — วิธีทำละเอียดที่สุด',
        guide: 'คู่มือภาษาอังกฤษที่ครอบคลุมเควสนี้',
        reguide: 'เว็บคู่มือของ Re: Star Ark',
        index: 'ดัชนีเควสทั้งหมดของวิกิ Fandom แยกตามพื้นที่',
        baha: 'กระทู้บอร์ดไต้หวันที่เป็นที่มาของข้อมูลแถวนี้',
        board: 'บอร์ด Re: Star Ark บน 巴哈 — ค้นหาชื่อเควสนี้ในบอร์ด',
        search: 'ค้นหาชื่อเควสนี้ใน Google',
      },
      counts: '{n} จาก {total} เควส · ยืนยันใน Re แล้ว {re} รายการ',
      noResults: 'ไม่พบเควสที่ตรงกับตัวกรอง',
      gap: 'จุดที่ยังขาด: รายการเควสหลักและเควสรองฉบับเต็มของ Re ยังไม่มีเผยแพร่ที่ไหนที่เข้าถึงได้ ถ้าอ่านชื่อเควสจากในเกมได้ บอก KK แล้วจะเพิ่มให้',
    },
    feedback: {
      title: 'แจ้งข้อมูลผิด',
      lede: 'ข้อมูลในเว็บนี้มาจากการค้นคว้าฝั่งเซิร์ฟไต้หวัน ยังไม่ได้ตรวจสอบในเกมไทย ถ้าเจอตรงไหนไม่ตรงกับในเกม บอกมาได้เลย นั่นคือทางเดียวที่มันจะถูกแก้',
      how: [
        'ชื่อที่เกมไทยเขียนจริง ๆ สะกดแบบที่เห็นในเกม',
        'มีรูปหน้าจอยิ่งดี รูปเดียวจบเลย',
        'ในเว็บเขียนว่าอะไร และในเกมเป็นอะไร',
      ],
      notReady: 'ยังไม่ได้เชื่อมฟอร์ม ระหว่างนี้ส่งข้อมูลให้ KK โดยตรงได้เลย',
      openNew: 'ฟอร์มไม่ขึ้น? เปิดในแท็บใหม่',
      after: 'เรื่องที่ยืนยันแล้วจะถูกติดป้าย “ทดสอบเองในเกม” ซึ่งเป็นระดับความน่าเชื่อถือสูงสุดของเว็บนี้',
    },
    companions: {
      title: 'จุติขุนพลและอาวุธเฉพาะตัว',
      lede: 'ขุนพลแทบทุกตัวมีอุปกรณ์เฉพาะตัวที่ตัวอื่นใส่ไม่ได้ และการจุติ (轉生) จะอัปเกรดอุปกรณ์ชิ้นนั้นพร้อมปลดล็อกสกิลใหม่ เรื่องสำคัญที่สุดในหน้านี้คือกลไกค่าขั้นต่ำ — พลาดแล้วแก้ไม่ได้ตลอดชีวิตตัวละคร',
      dataNote: 'ข้อมูลจากเซิร์ฟเวอร์ไต้หวัน (星飄) ซึ่งเปิดก่อนไทยประมาณ 1 ปี จึงแสดงชื่อจีนกำกับไว้ทุกชิ้นเพื่อเทียบกับไกด์ฝั่งไต้หวันได้ ชื่อไทยเป็นคำแปล ยังไม่ยืนยันกับไคลเอนต์ ยกเว้น ลิงคส์ ซึ่งเป็นชื่อในโปรโมชันไทย',
      howTitle: 'ระบบจุติทำงานอย่างไร',
      howReq: ['ขุนพลต้องมีเลเวล 100 ขึ้นไป', 'ทำเควสเฉพาะตัวของขุนพลตัวนั้นให้จบ', 'คุยกับ NPC ผู้กำหนด (能者)', 'ผ่านบททดสอบ (試煉)'],
      howPill: 'ขุนพลสายกิจกรรม/ไอเทมมอลล์ใช้ “ยาจุติ” (轉生丹) แทน',
      howUnknown: 'ยังไม่รู้: ชื่อ NPC ผู้กำหนดและหน้าตาของบททดสอบ — ไม่มีแหล่งข้อมูลสาธารณะระบุไว้ ต้องเช็กในเกมเอง',
      gainTitle: 'ได้อะไร',
      gain: ['รูปลักษณ์ใหม่ทั้งตัว', 'สกิลจุติใหม่ 1 สกิล', 'อัปเกรดอุปกรณ์เฉพาะตัวเป็นเวอร์ชันจุติ', 'ค่าสถานะโดยรวมสูงขึ้น'],
      floorTitle: 'กลไกค่าขั้นต่ำ — อ่านก่อนจุติ',
      floorIntro: 'หลังจุติ ระบบจะสุ่มแจกแต้มสถานะใหม่ (轉生點數) — ขุนพลสายมอลล์ได้ 130 แต้ม สายเควสได้ 126–129 แต้ม และขุนพลแต่ละตัวมีค่าขั้นต่ำกำกับอยู่',
      floorRuleUp: 'ค่าที่สุ่มได้สูงกว่าขั้นต่ำ → ล้าง (洗) ได้ตลอด',
      floorRuleDown: 'ค่าที่สุ่มได้ต่ำกว่าขั้นต่ำ → ล้างไม่ได้อีกเลย แม้จะกินยาหรือเลเวลอัปจนค่าขึ้นไปถึงทีหลังก็ตาม',
      floorExample: 'มารีที่ 1 มีค่าขั้นต่ำ WIS = 41 ถ้าจุติแล้วสุ่มได้ WIS 39 จะล้าง WIS ไม่ได้อีกเลย ต่อให้กินยาจน WIS เกิน 41 ก็ตาม',
      floorSafe: ['กินยาเพิ่มค่าสถานะให้เต็มก่อนจุติ หรือ', 'เล็งให้แต้มที่สุ่มได้สูงกว่าค่าขั้นต่ำทุกช่อง แล้วหลังจากนั้นจะล้างค่าใหม่กี่รอบก็ได้', 'แนะนำให้ล้างค่าสถานะ 1 ครั้งตอนเลเวล 20 และอีกครั้งก่อนจุติ'],
      floorPills: 'ถ้ากินยาเต็มก่อนจุติ ให้บวกเพิ่มอีก 48 จากตัวเลขข้างบน',
      floorsHead: 'ค่าขั้นต่ำที่รู้แล้ว',
      gradeTitle: 'อุปกรณ์เฉพาะตัวมี 3 ระดับ',
      grades: [
        ['อุปกรณ์เฉพาะพื้นฐาน (專屬裝備)', 'ติดตัวมาตั้งแต่รับขุนพล', '—'],
        ['อุปกรณ์เฉพาะหลังจุติ (轉生專屬裝備)', 'รางวัลจากการจุติ', 'ระดับของ 1 และพังไม่ได้ — ของถาวร ไม่ต้องซ่อม'],
        ['อุปกรณ์เฉพาะจากมอลล์ (商城專屬裝備)', 'ไอเทมมอลล์', 'อาวุธ “ทองคำ” ค่าสถานะสูงกว่ามาก ราว 3 เท่าของอุปกรณ์จุติ'],
      ],
      terminology: 'ขุนพลร่างมนุษย์ใส่ปลอกแขน (臂環) และเข็มกลัด (胸針) · ขุนพลร่างสัตว์ใส่ปลอกคอ (項圈) และอานม้า (馬鞍)',
      pattern: 'อุปกรณ์เฉพาะหลังจุติของสายมอลล์เป็นสูตรตายตัว — +50 ในค่าหลัก',
      thTitle: 'สถานะบนเซิร์ฟไทย',
      thStatus: [
        'ลิงคส์มาไทยแล้ว — แจกผ่าน “ถุงสุ่มลิงคส์” ในโปรโมชันเติมเงินต่อเนื่องรายวัน 26 ส.ค. – 2 ก.ย. 2569',
        'เควสเปลี่ยนอาชีพเลเวล 100 ของตัวละคร เปิดแล้ว 9 ก.ย. 2569 เปลี่ยนแล้วเลเวลลดเหลือ 1 — คนละระบบกับจุติขุนพล',
        'ระบบจุติขุนพลยังไม่มีประกาศอย่างเป็นทางการบนเซิร์ฟไทย แต่ไอเทมมอลล์เริ่มขาย “ถุงสุ่มจุติยาชิน” และ “ถุงสุ่มจุติสาวไข่มุก” แล้ว แปลว่าเนื้อหาจุติมาบางส่วนแล้ว ต้องเช็กในเกมเอง',
        'ไต้หวันเปิดระบบจุติ 31 ก.ค. 2025 พร้อมแมพกรุงเทพฯ และเปิดตัวลิงคส์ในแพตช์เดียวกัน ไทยมีแมพกรุงเทพฯ แล้ว จึงน่าจะถึงคิวเร็ว ๆ นี้',
      ],
      companion: 'ขุนพล',
      kind: 'ประเภท',
      pts: 'แต้มจุติ',
      exclusive: 'อุปกรณ์เฉพาะ',
      rebirthExclusive: 'อุปกรณ์เฉพาะหลังจุติ',
      rebirthSkill: 'สกิลจุติ',
      questGroup: 'สายเควสเนื้อเรื่อง',
      mallGroup: 'สายกิจกรรม/ไอเทมมอลล์ — ใช้ยาจุติ 130 แต้มทุกตัว',
      types: { phys: 'กายภาพ', magic: 'เวท', hybrid: 'กาย+เวท', gun: 'ปืน', bow: 'ธนู' },
      forms: { human: 'มนุษย์', beast: 'สัตว์' },
      spotlight: 'เจาะลึก',
      skills: 'สกิล',
      skillsHint: 'กดที่ชื่อขุนพลเพื่อดูสกิล',
      skillOpen: 'ดูสกิล',
      skillSp: 'SP',
      skillMaxShort: 'สูงสุด',
      skillUpgrade: 'อัปเกรดเป็น',
      skillRebirth: 'สกิลจุติ',
      skillLegacy: 'ค่า SP รูปแบบการโจมตี และคำอธิบาย มาจากข้อมูลเกมเวอร์ชันเก่าของ WLOHUB ไม่ใช่ Re',
      skillLegacyMark: 'เวอร์ชันเก่า',
      skillSourceNote: 'ชื่อสกิลและระดับสูงสุดมาจากตารางคอมมูนิตี้ของ Re (星飄) ครบทั้ง 25 ตัว ส่วนค่า SP รูปแบบการโจมตี และคำอธิบาย มาจาก WLOHUB ซึ่งมีข้อมูลเฉพาะเกมเวอร์ชันเก่า จึงมีแค่ 12 ตัว และตัวเลขเป็นของก่อน Re ชื่อสกิลภาษาไทยเป็นคำแปล',
      ways: {
        near: 'ระยะประชิด',
        dist: 'ระยะไกล',
        aid: 'สกิลสนับสนุน',
        buff: 'เพิ่มค่าสถานะ',
        single: 'เป้าหมายเดียว',
      },
      maxLv: 'ระดับสูงสุด',
      otherGear: 'อุปกรณ์อื่น',
      slots: {
        blade: 'อาวุธ · ใบมีด',
        sword: 'อาวุธ · ดาบ',
        wand: 'อาวุธ · คทา',
        club: 'อาวุธ · กระบอง',
        gun: 'อาวุธ · ปืน',
        bow: 'อาวุธ · ธนู',
        claw: 'อาวุธ · กรงเล็บ',
        weapon: 'อาวุธ',
        accessory: 'เครื่องประดับ',
        head: 'ศีรษะ',
        hand: 'มือ / แขน',
      },
      slotLabel: 'ช่องสวมใส่',
      slotInferred: 'อนุมาน',
      slotInferredHelp: 'ยังไม่มีแหล่งข้อมูลระบุช่องสวมใส่ อนุมานจากการที่ไอเทมไม่มีป้ายช่องในตารางคอมมูนิตี้ ซึ่งในตารางนั้นหมายถึงอาวุธ',
      slotConfirmedHelp: 'มีแหล่งข้อมูลระบุช่องสวมใส่ (หน้าไอเทมของ WLOHUB หรือป้ายช่องในตารางคอมมูนิตี้)',
      slotConflict: 'แหล่งข้อมูลไม่ตรงกัน — ดูหมายเหตุ',
      slotNoteHead: 'หมายเหตุเรื่องช่องสวมใส่',
      slotLegend: 'อุปกรณ์เฉพาะทุกชิ้นระบุช่องสวมใส่ไว้ ช่องที่ติดป้าย “อนุมาน” ยังไม่มีแหล่งข้อมูลระบุตรง ๆ แต่มาจากธรรมเนียมของตารางคอมมูนิตี้ที่ว่าอุปกรณ์เฉพาะซึ่งไม่มีป้ายช่องคืออาวุธ จาก 49 ชิ้น มีแหล่งยืนยัน 28 ชิ้น ที่เหลือเป็นการอนุมาน — และ WLOHUB ไม่มีหน้าข้อมูลของขุนพลสายมอลล์/Re 12 ตัวเลย',
      counts: 'ขุนพล {n} ตัว · จากเควส {quest} · จากมอลล์ {mall}',
    },
    footer: {
      source:
        'ที่มา: ตารางสูตรรวมของคอมมูนิตี้ Re 「星飄」 โดย 苦茶 และผู้ร่วมให้ข้อมูล อัปเดต 25 มิ.ย. 2025 → 30 พ.ค. 2026 ชื่อภาษาอังกฤษและไทยเป็นคำแปล ยกเว้นที่ระบุว่ายืนยันแล้ว',
      match: 'ให้จับคู่ไอเทมด้วยเลเวลไอเทมและค่าสถานะ ซึ่งไม่ขึ้นกับภาษา อย่าจับคู่ด้วยชื่อ',
      updated: 'ข้อมูล ณ วันที่',
    },
  },
};

export const t = (lang) => UI[lang] || UI[DEFAULT_LANG];
